version: '3.8'

services:
  vibe-kanban:
    build: .
    ports:
      - "9001:9001"
    volumes:
      # Mount local repositories directory
      - ./repos:/workspace/repos
      # Mount MCP servers directory for tool access
      - ./mcp-servers:/workspace/mcp-servers
      # Mount Claude configuration for persistence (optional - will use defaults if not present)
      - ./docker/claude-config:/root/.claude
      # Mount llmenv directory for configuration updates
      - .:/workspace/llmenv
    environment:
      - PORT=9001
      - NODE_ENV=production
      - LLMENV_ROOT=/workspace/llmenv
    working_dir: /workspace/repos
    stdin_open: true
    tty: true
    restart: unless-stopped
    
  # Optional: Add a development version that mounts more directories
  vibe-kanban-dev:
    build: .
    ports:
      - "9002:9001"
    volumes:
      - ./repos:/workspace/repos
      - ./mcp-servers:/workspace/mcp-servers
      - ./docker/claude-config-dev:/root/.claude
      - .:/workspace/llmenv
      # Mount additional development directories
      - ~/.ssh:/root/.ssh:ro
      - ~/.gitconfig:/root/.gitconfig:ro
    environment:
      - PORT=9001
      - NODE_ENV=development
      - LLMENV_ROOT=/workspace/llmenv
    working_dir: /workspace/repos
    stdin_open: true
    tty: true
    profiles:
      - dev